### ISSUE TITLE
Eliminar el commit de local_settings.py en master

### ISSUE THREAD

**Issue by moncalvillo** [Full-Tortuga/decide-full-tortuga-autenticacion#27]
No se deberia commitear el local_settings.py

**Comment by josrompoz1** [comment]
El fichero local_settings.py se subió por error. Revertir el pull request para meter dicho archivo no es complicado pero no solucionaría nada. Además ya que hay otro pull request encima. La solución es que cada uno cambie su local_setting.py para que le funcione el proyecto en local. El problema de este local_settings.py es la configuración de mongo. Simplemente habría que cambiar el usuario y la contraseña de mongo, y el host en caso de que fuera necesario.
