### ISSUE TITLE
Vista de formulario en blanco

### ISSUE THREAD

**Issue by marsamber** [Full-Tortuga/decide-full-tortuga-autenticacion#56]
Cuando intento acceder a la url "/authentication/login_form", en vez de aparecerme el formulario en cuestión, me aparece una página en blanco.
Creo que se debe a la falta del archivo JavaScript que importa el proyecto de React (main.6bd86252.js).

**Comment by carvilgar1** [comment]
Los staticos perdidos ya se encuentran en la rama main
